import { jsPDF } from 'jspdf'
import { GenomicRegion, formatGenomicRegion } from '../types/region'
import { Track } from '../types/track'
import { computePdfLayout } from './pdfLayout'

/**
 * PDF export surface.
 *
 * - `exportBrowserReport` — the existing text-only summary (kept as-is for
 *   backwards compatibility).
 * - `exportViewAsPdf` — embeds the composite browser view (rasterized at
 *   high DPI) into a landscape A4 PDF.  The view is paginated when it is
 *   taller than a single page: each page gets its own header band plus the
 *   appropriate vertical slice of the view.
 */
export class PDFExporter {
  static exportBrowserReport(genomeName: string, region: GenomicRegion, tracks: Track[]) {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    })

    const title = `WashU Epigenome Browser Report - ${genomeName.toUpperCase()}`
    const regionText = `View Region: ${formatGenomicRegion(region)}`
    const dateText = `Exported: ${new Date().toLocaleString()}`

    // Header
    doc.setFillColor(15, 23, 42) // slate-900
    doc.rect(0, 0, 297, 25, 'F')

    doc.setTextColor(56, 189, 248) // cyan-400
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(title, 14, 12)

    doc.setTextColor(203, 213, 225) // slate-300
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`${regionText}  |  ${dateText}`, 14, 19)

    // Tracks summary list
    let yPos = 35
    doc.setTextColor(30, 41, 59)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(`Active Genomic Tracks (${tracks.length})`, 14, yPos)
    yPos += 8

    tracks.forEach((track, idx) => {
      if (yPos > 180) {
        doc.addPage()
        yPos = 20
      }

      doc.setFillColor(241, 245, 249)
      doc.roundedRect(14, yPos, 269, 14, 2, 2, 'F')

      // Color badge
      const hexColor = track.options.color || '#38bdf8'
      doc.setFillColor(hexColor)
      doc.circle(20, yPos + 7, 3, 'F')

      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(15, 23, 42)
      doc.text(`${idx + 1}. ${track.name}`, 26, yPos + 8)

      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100, 116, 139)
      const meta = track.metadata ? `Assay: ${track.metadata.assay || 'N/A'} | Cell: ${track.metadata.cell || 'N/A'}` : `Type: ${track.type}`
      doc.text(meta, 180, yPos + 8)

      yPos += 18
    })

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text('Generated by WashU Epigenome Browser v3 (Vue Edition) - https://epigenomegateway.wustl.edu/', 14, 200)

    doc.save(`epigenome_browser_${genomeName}_${region.chr}_${region.start}.pdf`)
  }

  /**
   * Export the composite browser view (canvas) as a landscape A4 PDF.
   *
   * The view image is sliced vertically into chunks that fit a landscape A4
   * page (after reserving a small header band per page).  Each page gets a
   * slate header with title/region/date and a footer credit, matching the
   * visual style of `exportBrowserReport`.
   */
  static exportViewAsPdf(
    imageBlob: Blob,
    opts: {
      genomeName: string
      region: GenomicRegion
      trackCount: number
    }
  ): void {
    const { genomeName, region, trackCount } = opts
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    })

    const pageW = doc.internal.pageSize.getWidth() // 297 mm
    const pageH = doc.internal.pageSize.getHeight() // 210 mm

    const headerH = 22
    const footerH = 8
    const topPad = 4
    const botPad = 4
    const marginL = 10
    const marginR = 10
    const viewW = pageW - marginL - marginR
    const viewHPerPage = pageH - headerH - topPad - footerH - botPad

    const title = `WashU Epigenome Browser — ${genomeName.toUpperCase()}`
    const subtitle = `${formatGenomicRegion(region)}   ·   ${trackCount} track(s)   ·   ${new Date().toLocaleString()}`
    const footerText = 'Generated by WashU Epigenome Browser v3 (Vue Edition)'

    const img = new Image()
    img.onload = () => {
      const totalW = img.width
      const totalH = img.height

      // Always fill the usable page width (never shrink to fit both dims —
      // the old `Math.min(scaleX, scaleY)` made srcPerPage ≥ totalH, so the
      // pagination branch below was dead code and tall views always came out
      // as one squashed page).
      const layout = computePdfLayout(totalW, totalH, viewW, viewHPerPage)
      const offsetX = marginL + (viewW - layout.dstWUsed) / 2
      const offsetY = topPad + headerH

      function drawChrome(pageNo: number) {
        doc.setFillColor(15, 23, 42)
        doc.rect(0, 0, pageW, headerH, 'F')

        doc.setTextColor(56, 189, 248)
        doc.setFontSize(14)
        doc.setFont('helvetica', 'bold')
        doc.text(title, marginL, 14)

        doc.setTextColor(203, 213, 225)
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        doc.text(subtitle, marginL, 20)

        doc.setTextColor(148, 163, 184)
        doc.setFontSize(8)
        doc.text(`p. ${pageNo}  |  ${footerText}`, pageW - marginR, pageH - 3, { align: 'right' })
      }

      const chunkCanvas = document.createElement('canvas')

      layout.slices.forEach((slice, p) => {
        chunkCanvas.width = totalW
        chunkCanvas.height = slice.srcH
        const cctx = chunkCanvas.getContext('2d')!
        cctx.drawImage(img, 0, slice.srcY, totalW, slice.srcH, 0, 0, totalW, slice.srcH)

        if (p > 0) doc.addPage()
        drawChrome(p + 1)

        const imgDataUrl = chunkCanvas.toDataURL('image/png')
        doc.addImage(imgDataUrl, 'PNG', offsetX, offsetY, layout.dstWUsed, slice.dstH)
      })

      doc.save(`epigenome_browser_${genomeName}_${region.chr}_${region.start}_view.pdf`)
    }

    img.src = URL.createObjectURL(imageBlob)
  }
}
